#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
echo "sxhkd running" > /home/dan/dotfiles/screenlog

# MONITOR SETUP
monitors=$(bspc query -M --names)
TOPWIDE=("DisplayPort-0" "DisplayPort-1" "DisplayPort-2" "DisplayPort-3" "DP-1")
TOP=("HDMI-A-0")
BOTTOM=("eDP" "eDP-1", "eDP1")

available_topwide=()
available_top=()
available_bottom=()

array_contains () {
    local seeking=$1; shift
    local in=1
    for element; do
        if [[ $element == "$seeking" ]]; then
            in=0
            break
        fi
    done
    return $in
}

echo "monitors: $monitors" >> /home/dan/dotfiles/screenlog
for value in $monitors
do
    array_contains $value ${TOP[@]} && available_top+=("$value")
    array_contains $value ${TOPWIDE[@]} && available_topwide+=("$value")
    array_contains $value ${BOTTOM[@]} && available_bottom+=("$value")
done

echo "topwide: $available_topwide" >> /home/dan/dotfiles/screenlog
echo "bottom: $available_bottom" >> /home/dan/dotfiles/screenlog

if [ "${#available_top[@]}" -eq "1" ] && [ "${#available_bottom[@]}" -eq "1" ]; then
    BOTTOM=${available_bottom[0]}
    TOP=${available_top[0]}
    xrandr --output $TOP --above $BOTTOM --auto
    bspc wm -O $TOP $BOTTOM
    bspc monitor $TOP -d 6 7 8 9 10
    bspc monitor $BOTTOM -d 1 2 3 4 5

    MONITOR=$TOP polybar top &
    MONITOR=$BOTTOM polybar top &
    nitrogen --set-zoom-fill --random ~/Pictures/wallpapers/art/dual_screen_top/

elif [ "${#available_topwide[@]}" -eq "1" ] && [ "${#available_bottom[@]}" -eq "1" ]; then
    BOTTOM=${available_bottom[0]}
    TOPWIDE=${available_topwide[0]}

    xrandr --output $BOTTOM \
        --primary \
        --mode 1920x1080 \
        --pos 760x1440 \
        --rotate normal \
    --output $TOPWIDE \
        --above $BOTTOM \
        --mode 3440x1440 \
        --pos 0x0 \
        --rotate normal
    bspc wm -O $TOPWIDE $BOTTOM
    bspc monitor $TOPWIDE -d 1 2 3
    bspc monitor $BOTTOM -d 4 5 6 7 8 9 10

    MONITOR=$TOPWIDE polybar top &
    MONITOR=$BOTTOM polybar top &
    nitrogen --set-zoom-fill --random ~/Pictures/wallpapers/art/dual_screen_top/
elif [ "${#available_bottom[@]}" -eq "1" ]; then
    BOTTOM=${available_bottom[0]}
    bspc monitor $BOTTOM -d 1 2 3 4 5 6 7 8 9 10
    MONITOR=$BOTTOM polybar top &
    nitrogen --set-zoom-fill --random ~/Pictures/wallpapers/art/single_screen/ &
else
    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
    polybar top &
    nitrogen --set-zoom-fill --random ~/Pictures/wallpapers/art/single_screen/ &

fi



bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
