#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor HDMI-2 -d 6 7 8 9 10
bspc monitor eDP-1 -s HDMI-2

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off


