#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# For an aditional monitor setup
if [ "$(bspc query -M | wc -l)" -eq "2" ]; then

	bspc monitor eDP-1 -d 1 2 3 4 5 
	bspc monitor HDMI-2 -d 6 7 8 9 10
	
	# Initiate the polybar for the external monitor and the laptop
       	polybar topext &	
	polybar top &

else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
	# Initial the polybar for just the main monitor

	polybar top &
fi


bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
